// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyixN65j5K0hkRYiBZfdb_QgeikdAv-j0',
    appId: '1:1092967405162:web:be69db8a9460687b11dc13',
    messagingSenderId: '1092967405162',
    projectId: 'fl-calculadora-ia',
    authDomain: 'fl-calculadora-ia.firebaseapp.com',
    storageBucket: 'fl-calculadora-ia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUt2r3-WpOykxf9uVMnwvfgAY4dGkamhA',
    appId: '1:1092967405162:android:69b454c109eb4d0111dc13',
    messagingSenderId: '1092967405162',
    projectId: 'fl-calculadora-ia',
    storageBucket: 'fl-calculadora-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf7XXslXuoatVnkjJOFiCtnQUBZhRZUGY',
    appId: '1:1092967405162:ios:7e44d6555216d6cf11dc13',
    messagingSenderId: '1092967405162',
    projectId: 'fl-calculadora-ia',
    storageBucket: 'fl-calculadora-ia.firebasestorage.app',
    iosBundleId: 'com.example.flCalculadoraIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf7XXslXuoatVnkjJOFiCtnQUBZhRZUGY',
    appId: '1:1092967405162:ios:7e44d6555216d6cf11dc13',
    messagingSenderId: '1092967405162',
    projectId: 'fl-calculadora-ia',
    storageBucket: 'fl-calculadora-ia.firebasestorage.app',
    iosBundleId: 'com.example.flCalculadoraIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyixN65j5K0hkRYiBZfdb_QgeikdAv-j0',
    appId: '1:1092967405162:web:9bf296752d09f96011dc13',
    messagingSenderId: '1092967405162',
    projectId: 'fl-calculadora-ia',
    authDomain: 'fl-calculadora-ia.firebaseapp.com',
    storageBucket: 'fl-calculadora-ia.firebasestorage.app',
  );
}
